### ISSUE TITLE
TAR-achive is not deletable after browsing unless closing IDEA

### ISSUE THREAD

**Issue by Tom-BGR** [b3er/idea-archive-browser#14]
Hi,
I really love this Plugin. It's very useful. But unfortunately when I've opened a TAR-archive, it is no more deletable or can be overwritten by any code. This is just possible when exiting IDEA.

The error is an IOException. It feels like the archive doesn't get closed after showing the content in the tree.
Kind regards, Thomas

**Comment by dangoodman** [comment]
Same issue here with zip archives.
