### ISSUE TITLE
Doesn't Work on Windows

### ISSUE THREAD

**Issue by mfreeman-xtivia** [b3er/idea-archive-browser#15]
Does not work on Windows10 with 2019.1.3

Displays top/1st level folders in a JAR file but then clicking on the arrow next to the directory shows no further decomposition of the archive and then the arrow next to the folder dissapears

**Comment by mfreeman-xtivia** [comment]
Still open even in most up to date version of IntelliJ IDEA.

**Comment by hauntingEcho** [comment]
I'm not seeing this issue on Windows 10, IDEA Community 2020.2 installed today with no other plugins, and opening `debezium-server-dist-1.3.1.Final-runner.jar` from the Debezium project
