### ISSUE TITLE
Support .gem suffix

### ISSUE THREAD

**Issue by donv** [b3er/idea-archive-browser#16]
Hi!

Great plugin!  Very useful!

I am browsing JAR files nicely, and I can browse a `.tar.gz` file, but only if I rename it to `.tar`

In my case it is a `.gem` file from RubyGems, but the content is `.tar.gz`.

Renaming to 

* `.tgz` does not work
* `.tar.gz` does not work
* `.gem` does not work
* `.tar` works

I am including the file in question.  All help is appreciated.  I'll do a PR if you wish.

**Comment by donv** [comment]
[sqldroid-1.1.0.beta.4-java.tar.gz](https://github.com/b3er/idea-archive-browser/files/3604352/sqldroid-1.1.0.beta.4-java.tar.gz)

**Comment by donv** [comment]
My bad, the `.gem` file is actually just a `.tar` file with `.gz` files inside.

It would be great if `.gem` could be an alias for `.tar` and the `.gz` files inside could be browsable as well.

**Comment by b3er** [comment]
Added support in version 0.20
