### ISSUE TITLE
Cannot open .apk archives

### ISSUE THREAD

**Issue by StefanLobbenmeier** [b3er/idea-archive-browser#17]
I can open .apk files with 7-zip and also this plugin support opening them when I rename them to .zip

Could you add .apk to the "known file endings" list? I Already tried the IntelliJ settings Editor -> File Types -> Archive -> Add -> "*.apk" - but IntelliJ gave me an error that this is reserved

**Comment by StefanLobbenmeier** [comment]
Update: I checked the code and found this line:

https://github.com/b3er/idea-archive-browser/blob/8c2d006e4bdba48a34b1bf9bb224343b7e2780db/src/main/kotlin/com/github/b3er/idea/plugins/arc/browser/plugin.kt#L70

I am not sure what stops IntelliJ from allowing this plugin to open .apk files - maybe its own Android support is "overriding" this apk support?

**Comment by StefanLobbenmeier** [comment]
Workaround for now is using IntelliJs own capabilities:
1. Copy path of apk (Ctrl + Shift + C)
2. Click Build -> Analyze Apk (or use Ctrl + Shift + A and search for Analyze Apk)
3. Paste the path in the "Select Path" windows" and click "OK"

A tab like this opens (might be even better):

![image](https://user-images.githubusercontent.com/36509607/68284293-7f9b0800-007d-11ea-978a-964354c354a2.png)

**Comment by b3er** [comment]
AAR and APK file types are reserved for android plugin and cannot be reassigned to any other plugin
