### ISSUE TITLE
Locks files on Windows after Intellij 2019.3 update

### ISSUE THREAD

**Issue by leonard84** [b3er/idea-archive-browser#18]
Since the  2019.3 update I get a lot of ` Failed to clean project: Failed to delete ...` errors when running `mvn clean install`. Before that I had no issues.
It seems that the plugin keeps the file handles open. In my case it were always `.deb` files, but that might just be the result of file order.

**Comment by igreenfield** [comment]
I have the same issue!

**Comment by leonard84** [comment]
Seems to be the same or similar issue as #14

**Comment by b3er** [comment]
Should be fixed in 0.20
