### ISSUE TITLE
Cannot browse .log.gz archive from slf4j/logback

### ISSUE THREAD

**Issue by NIA** [b3er/idea-archive-browser#2]
Thanks for a great plugin 👍 , I was able to browse both .zip and .gz archives, but here is one problem

In my application I have logging via logback, it is configured with such appender:

```xml
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/client.log</file>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logs/client.%d{yyyy-MM-dd-HH-mm}.%i.log.gz</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>10MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
        </rollingPolicy>
        <encoder>
            <charset>UTF-8</charset>
            <Pattern>
                %n%date{HH:mm:ss.SSS} %-5level %t %msg%n%throwable{full}
            </Pattern>
        </encoder>
    </appender>
```
It produces files like this: [client.2017-09-15-14-27.0.log.gz](https://github.com/b3er/idea-archive-browser/files/1306195/client.2017-09-15-14-27.0.log.gz)

I was not able to browse it in the project view, the "expand" button simply is not showing.
![image](https://user-images.githubusercontent.com/26939/30480633-6d732b98-9a23-11e7-999c-f7168e717a3d.png)
But I am able to open this file with 7zip or WinRAR
What could be wrong?

**Comment by b3er** [comment]
Thanks for writing!
Fixed in 0.10
