### ISSUE TITLE
Needs basic documentation

### ISSUE THREAD

**Issue by oche-jay** [b3er/idea-archive-browser#20]
Sounds like a really useful plugin but there's no information about how to use it. My use case is that I want to inspect a snapshot jar file downloaded from a repository to debug an issue I am seeing, but I have no idea how to do this. I am probably missing something very obvious but at least a brief description on how to use the plugin would have helped.

**Comment by qiaoxingxing** [comment]
after install the plugin,open menu: file - open..., now you can brower jar file  as directory
