### ISSUE TITLE
Can you add support for aar files

### ISSUE THREAD

**Issue by mcxinyu** [b3er/idea-archive-browser#21]
Can you add support for aar files?

**Comment by hauntingEcho** [comment]
it looks like they've already got it: https://github.com/b3er/idea-archive-browser/blob/8c2d006e4bdba48a34b1bf9bb224343b7e2780db/src/main/kotlin/com/github/b3er/idea/plugins/arc/browser/plugin.kt#L70

**Comment by mcxinyu** [comment]
But it doesn't seem to be working

![image](https://user-images.githubusercontent.com/9566116/99635513-0cdcaf00-2a7d-11eb-8233-b67275d7545f.png)

**Comment by b3er** [comment]
AAR and APK file types are reserved for android plugin and cannot be reassigned to any other plugin
