### ISSUE TITLE
treat .resource file as zip

### ISSUE THREAD

**Issue by wrnunzio** [b3er/idea-archive-browser#22]
Hello b3er,
At the moment all salesforce developer (that are using IntelliJ) are unable to open directly some file that are generated by the platform.
Those file have this extension ".resource" and currently it doesn't seems to be supported by your plugin.
As specified in the title , those file are just normal ".zip" but with a different extension. 
If there is something that u can do make this association it would be awesome.

Thanks,
NC.

**Comment by b3er** [comment]
If you use 2020.3 version of idea, you can do this by assigning a "*.resource" pattern to "Archive" or "7zip archive" (depending on archive type you want), just go to Preferences->File Types
