### ISSUE TITLE
Allow user-configurable file extensions

### ISSUE THREAD

**Issue by conorgriffin** [b3er/idea-archive-browser#27]
We use some custom extensions for archives that are actually just zip files.  It would be useful to be able to add custom extension mappings.

For example we have a custom extension `.wsar` which is actually a `.zip` file.  If the plugin allowed some configuration that permitted a mapping of `.wsar` -> `.zip` then our files would be treated as zip.  This is similar to the request in #25 but is more generic while permitting usage for custom extensions which may not be globally recognised as using a particular compression format.

**Comment by b3er** [comment]
If you use 2020.3 version or later, you can do this by assigning any file extension to "Archive" or "7zip archive" (depending on archive type you want), just go to Preferences->File Types
