### ISSUE TITLE
Feature request: add setting to add archive formats

### ISSUE THREAD

**Issue by borissmidt** [b3er/idea-archive-browser#31]
I really like your plugin and it would be nice if it was possible to add other extensions to the plugin.
For example xlsx is also a zip but there is no way to add the detection of it for the plugin.

**Comment by b3er** [comment]
@borissmidt You can do this in Preferences->Editor->File types:
- select "Archive (Archive Browser)" in "Recognized File Types" pane 
- add your pattern in "File name patterns" list (eg. "*.xlsx")

**Comment by borissmidt** [comment]
Nice it works, thank you! Maybe it would be a good idea to add it to the documentation of the plugin?
