### ISSUE TITLE
Support for PyCharm and others

### ISSUE THREAD

**Issue by aspidxt** [b3er/idea-archive-browser#4]
Is it possible to implement this plugin to support other JetBrains products such as PyCharm?

**Comment by andrewprofile** [comment]
Yes, check https://github.com/b3er/idea-archive-browser/pull/5

**Comment by bluelovers** [comment]
hope for webstorm too

**Comment by andrewprofile** [comment]
Yes, for all product of JetBrains

**Comment by andrewprofile** [comment]
Yes, for all products of JetBrains

**Comment by b3er** [comment]
Just updated, thanks!
